# Generated by Django 6.0.4 on 2026-04-30 16:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Chờ xử lý'), ('Confirmed', 'Đã xác nhận'), ('Shipped', 'Đang giao'), ('Active', 'Đang thuê'), ('Returned', 'Đã trả'), ('Cancelled', 'Đã hủy')], default='Pending', max_length=20, verbose_name='Trạng thái')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng tiền (k)')),
                ('deposit_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tiền cọc (k)')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Chuyển khoản'), ('momo', 'Momo'), ('zalopay', 'ZaloPay'), ('cash', 'Tiền mặt')], default='bank_transfer', max_length=20, verbose_name='Phương thức thanh toán')),
                ('rental_start', models.DateField(verbose_name='Ngày bắt đầu thuê')),
                ('rental_end', models.DateField(verbose_name='Ngày trả')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Tên khách hàng')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('customer_address', models.TextField(verbose_name='Địa chỉ giao hàng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đặt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
            ],
            options={
                'verbose_name': 'Đơn thuê',
                'verbose_name_plural': 'Đơn thuê',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10, verbose_name='Size')),
                ('daily_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá/ngày (k)')),
                ('rental_days', models.IntegerField(verbose_name='Số ngày thuê')),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Thành tiền (k)')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn',
                'verbose_name_plural': 'Chi tiết đơn',
            },
        ),
    ]
