# Generated by Django 6.0.4 on 2026-04-30 16:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Tên nhân vật')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('status', models.CharField(choices=[('Available', 'Còn hàng'), ('In Stock', 'Trong kho'), ('Limited Availability', 'Số lượng có hạn'), ('Out of Stock', 'Hết hàng')], default='Available', max_length=30, verbose_name='Trạng thái')),
                ('rental_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá thuê (k/ngày)')),
                ('accent_color', models.CharField(default='#7C3AED', max_length=7, verbose_name='Màu chủ đạo')),
                ('image', models.ImageField(blank=True, upload_to='characters/', verbose_name='Ảnh chính')),
                ('components', models.JSONField(blank=True, default=list, help_text='Danh sách thành phần trang phục [{"icon": "🎩", "name": "Mũ"}]', verbose_name='Thành phần trang phục')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2, verbose_name='Đánh giá')),
                ('review_count', models.IntegerField(default=0, verbose_name='Số đánh giá')),
                ('sizes_available', models.JSONField(blank=True, default=list, help_text='Danh sách size ["S", "M", "L", "XL"]', verbose_name='Size có sẵn')),
                ('origin_game', models.CharField(blank=True, max_length=100, verbose_name='Game/Anime gốc')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
            ],
            options={
                'verbose_name': 'Nhân vật',
                'verbose_name_plural': 'Nhân vật',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CharacterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='characters/gallery/', verbose_name='Ảnh')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Chú thích')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='characters.character', verbose_name='Nhân vật')),
            ],
            options={
                'verbose_name': 'Ảnh bổ sung',
                'verbose_name_plural': 'Ảnh bổ sung',
                'ordering': ['order'],
            },
        ),
    ]
